#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_memory_limit --value=64M

#=================================================
# ACTIVATE MAINTENANCE MODE
#=================================================

ynh_maintenance_mode_ON

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=language --value=$(grep WPLANG $install_dir/wp-config.php | cut -d"'" -f4)

# Fix multisite as a boolean
if [ "${multisite,,}" = "yes" ]; then
	ynh_app_setting_set --key=multisite --value=1
	multisite=1
elif [ "${multisite,,}" = "no" ]; then
	ynh_app_setting_set --key=multisite --value=0
	multisite=0
fi

#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# SAVE THE CONFIG FILE IF IT HAS BEEN MODIFIED
#=================================================

ynh_backup_if_checksum_is_different "$install_dir/wp-config.php"

#=================================================
# CONFIGURE MULTISITE
#=================================================

ynh_script_progression "Configuring multisite..."

if [ $multisite -eq 1 ]
then
	ynh_replace --match="#--MULTISITE--" --replace="" --file=/etc/nginx/conf.d/$domain.d/$app.conf

    ynh_store_file_checksum "/etc/nginx/conf.d/$domain.d/$app.conf"

	ynh_systemctl --service=nginx --action=reload

	db_prefix=$(grep '^$table_prefix' "$install_dir/wp-config.php" | sed "s/.*'\(.*\)'.*/\1/" )

	ynh_replace --match="__DB_PREFIX__" --replace="$db_prefix" --file=../conf/sql/multisite.sql
	ynh_replace --match="__APP__" --replace="$app" --file=../conf/sql/multisite.sql
	ynh_replace --match="__LENGTH__" --replace="$((${#app} + 108))" --file=../conf/sql/multisite.sql

	ynh_mysql_db_shell < ../conf/sql/multisite.sql
	plugin_network="--network"
else
	multisite=0
	db_prefix=$(grep '^$table_prefix' "$install_dir/wp-config.php" | sed "s/.*'\(.*\)'.*/\1/" )

	ynh_replace --match="__DB_PREFIX__" --replace="$db_prefix" --file=../conf/sql/single.sql
	ynh_replace --match="__APP__" --replace="$app" --file=../conf/sql/single.sql
	ynh_replace --match="__LENGTH__" --replace="$((${#app} + 108))" --file=../conf/sql/single.sql

	ynh_mysql_db_shell < ../conf/sql/single.sql
	plugin_network=""
	if ynh_permission_has_user --permission="main" --user="visitor"
	then
		ynh_replace --match="//--PUBLIC--define" --replace="define" --file=$install_dir/wp-config.php
	fi
fi
ynh_app_setting_set --key=multisite --value=$multisite

#=================================================
# FILES & DIRECTORIES
#=================================================

ynh_script_progression "Set file and directories ownership"

mkdir -p $install_dir/wp-content/uploads
mkdir -p $install_dir/wp-content/temp
chown -R $app:www-data "$install_dir"
find "$install_dir" -type d -exec chmod 750 {} \;
find "$install_dir" -type f -exec chmod 640 {} \;
find "$install_dir/wp-content/uploads" -type d -exec chmod 770 {} \;
find "$install_dir/wp-content/temp" -type d -exec chmod 770 {} \;
setfacl -Rm d:g:www-data:rwX "$install_dir/wp-content/uploads"
setfacl -Rm d:g:www-data:rwX "$install_dir/wp-content/temp"

#=================================================
# STORE THE CHECKSUM OF THE CONFIG FILE
#=================================================

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum "$install_dir/wp-config.php"

#=================================================
# CREATE A CRON TASK FOR AUTOMATIC UPDATE
#=================================================

echo "# Reach everyday wp-cron.php to trig the internal WordPress cron.
0 3  *  *  * $app php$php_version  $install_dir/wp-cron.php" > /etc/cron.d/$app

#=================================================
# UPGRADE FAIL2BAN
#=================================================

ynh_script_progression "Reconfiguring Fail2Ban..."

ynh_config_add_fail2ban --logpath="/var/log/auth.log" --failregex="Authentication (attempt for unknown user|failure for) .* from <HOST>"

#=================================================
# REMOVE WP-CLI.PHAR
#=================================================

ynh_safe_rm $install_dir/wp-cli.phar

#=================================================
# DEACTIVE MAINTENANCE MODE
#=================================================

ynh_maintenance_mode_OFF

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
